

from typing import Protocol
from blocks.blockprotocol import ItemProtocol
from blocks.items import FoodProtocol
from maths.types import Location, Direction
from blocks import BlockProtocol

class ModelAPIProtocol(Protocol):

    @staticmethod
    def get_loc() -> Location: ...
    @staticmethod
    def get_block(pos: Location) -> BlockProtocol: ...
    @staticmethod
    def get_block_xyz(x: int, y: int, z: int) -> BlockProtocol: ...
    @staticmethod
    def has_inventory_space(quantity: int) -> bool: ...
    @staticmethod
    def get_inventory() -> dict[ItemProtocol, int]: ...
    @staticmethod
    def get_tools() -> list[ItemProtocol]: ...
    @staticmethod
    def try_walk(direction: Direction) -> bool: ...
    @staticmethod
    def try_mine(loc: Location) -> bool: ...
    @staticmethod
    def try_eat(food: FoodProtocol) -> bool: ...